name: Publish

on: push

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: tradukaten.app
            asset_name: tradukaten-${{ matrix.ver }}-linux-amd64
          - os: windows-latest
            artifact_name: tradukaten.app
            asset_name: tradukaten-${{ matrix.ver }}-windows-amd64
          - os: macos-latest
            artifact_name: tradukaten.app
            asset_name: tradukaten-${{ matrix.ver }}-macos-amd64

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: make

      - name: Test
        run: make test

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
