name: Release

on: [push]

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            os_name: ubuntu
            extension: app

          - os: windows-latest
            os_name: windows
            extension: exe

          - os: macos-latest
            os_name: macos
            extension: app

    steps:
      - name: Install dependencies
        run: choco install --verbose mingw make winflexbison3
        if: startsWith(matrix.os, 'windows')

      - uses: actions/checkout@v2
      - name: Build
        run: make

      - name: Run tests
        run: make test

      - name: Get Version
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Get Version Name
        id: get_version_name
        env:
          VERSION_WITHOUT_V: ${{ steps.get_version.outputs.version-without-v }}
        run: |
          VERSION_NAME=${VERSION_WITHOUT_V//./_}
          echo '::set-output name=version_name::$VERSION_NAME'

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: tradukaten.${{ matrix.extension }}
          asset_name: tradukaten-${{ matrix.os_name }}-${{ steps.get_version_name.outputs.version_name }}.${{ matrix.extension }}
          tag: ${{ github.ref }}
