name: Release

on: [push]

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Install dependencies
        run: choco install --verbose mingw make winflexbison3
        if: startsWith(matrix.os, 'windows')
    
      - uses: actions/checkout@v2
      - name: Build
        run: make

      - name: Run tests
        run: make test

      - name: Get the version
        id: get_version
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/tradukaten.app
          asset_name: tradukaten-${{ matrix.os }}-${{ steps.get_version.outputs.VERSION }}
          tag: ${{ github.ref }}
