name: Release

on: [push]

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            os_name: ubuntu
            original_extension: "app"
            result_extension: ""

          - os: windows-latest
            os_name: windows
            original_extension: "exe"
            result_extension: ".exe"

    steps:
      - name: Install dependencies
        run: choco install --verbose mingw make winflexbison3
        if: startsWith(matrix.os, 'windows')

      - uses: actions/checkout@v2
      - name: Build
        run: make

      - name: Run tests
        run: make test

      - name: Get Version
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Get Replaced Version
        id: get_replaced_version
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: frabert/replace-string-action@v2.0
        with:
          pattern: '\.'
          string: ${{ steps.get_version.outputs.version-without-v }}
          replace-with: "_"
          flags: "g"

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: tradukaten.${{ matrix.original_extension }}
          asset_name: tradukaten-${{ matrix.os_name }}-${{ steps.get_replaced_version.outputs.replaced }}${{ matrix.result_extension }}
          tag: ${{ github.ref }}
