name: Release

on: [push]

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            os_name: ubuntu
            extension: app

          - os: windows-latest
            os_name: windows
            extension: exe

          - os: macos-latest
            os_name: macos
            extension: app

    steps:
      - name: Install dependencies
        run: choco install --verbose mingw make winflexbison3
        if: startsWith(matrix.os, 'windows')

      - uses: actions/checkout@v2
      - name: Build
        run: make

      - name: Run tests
        run: make test

      - name: Get Version
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Get Replaced Version
        uses: mad9000/actions-find-and-replace-string@2
        id: get_replaced_version
        with:
          source: ${{ steps.get_version.outputs.version-without-v }}
          find: "."
          replace: "_"

      - name: Set Environment with Version
        id: set_env_with_version
        env:
          VERSION: ${{ steps.get_replaced_version.outputs.value }}
        run: echo "VERSION_NAME=$(echo $VERSION)" >> $env:GITHUB_ENV

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: tradukaten.${{ matrix.extension }}
          asset_name: tradukaten-${{ matrix.os_name }}-${{ env.VERSION_NAME }}.${{ matrix.extension }}
          tag: ${{ github.ref }}
